### ISSUE TITLE
Thumb Drawable Incorrectly Position

### ISSUE THREAD

**Issue by LogicalDesign** [apptik/MultiSlider#15] opened 2015-11-25 21:46 UTC
When using a custom Thumb Drawable, the position of the elements are not correctly lined up.

![activitysearch_sliderbarbutton_up 2x](https://cloud.githubusercontent.com/assets/3293260/11410221/87a2b8b4-937a-11e5-9168-e674070dbb9b.png)

![thumb_offs](https://cloud.githubusercontent.com/assets/3293260/11410135/e86a4528-9379-11e5-9e59-991c5a28e98c.png)

Creating a 9patch file out of that Drawable, the position is set correctly.

![activitysearch_sliderbarbutton_up 9](https://cloud.githubusercontent.com/assets/3293260/11410204/76661adc-937a-11e5-9510-64d35d42360c.png)

![thumbs_correct](https://cloud.githubusercontent.com/assets/3293260/11410253/c30df5bc-937a-11e5-937e-837a4fbcc447.png)

But when using the 9patch files to make a up/down state for the Thumbs it was incorrectly positioned again.
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Down -->
    <item android:drawable="@drawable/sliderbarbutton_down" android:state_enabled="true" android:state_pressed="true" />
    <!-- Up -->
    <item android:drawable="@drawable/sliderbarbutton_up" android:state_enabled="true" />
</selector>
```

**Comment by djodjoni** [comment] 2015-11-26 00:36
I cannot reproduce this. Can you send me some sample code that does? 
If you can base it on the examples module it would be great!
Thx!

**Comment by LogicalDesign** [comment] 2015-11-27 03:14
I've been looking into trying to reproduce it within your sample code, but it doesn't seem to happen. Checked also using all my app's styling within there and still seems fine.

Maybe it's a library I'm using? I'm not too sure what could have caused that issue.

**Comment by djodjoni** [comment] 2015-11-28 19:18
it would be weird if another library is interfering with your views. It could be probably in your code, some settings you make at some point. Do you programmatically change your view in some way ?

**Comment by LogicalDesign** [comment] 2015-11-28 22:27
Nope, I wasn't doing any changes in code, I was just trying to lay it out in xml first.

**Comment by djodjoni** [comment] 2015-12-12 21:46
closing this as not reproducible

**Closed by djodjoni** 2015-12-12 21:46 UTC
Labels: wontfix
